LLVM MinGW compatibility improvements (#454)
* Use standard C++ suffixes for integer literals

* Don't mix static and export

This fixes the following clang compilation error:
"cannot combine with previous 'static'"

* Add a compile-time option to disable slim_event_t

It uses ReadAcquire, WriteRelease which are not
defined in MinGW.

* Remove deprecated STRSAFE_PCNZCH

From strsafe.h:
"Deprecated, use the base types instead"

---------

Co-authored-by: Duncan Horn <40036384+dunhor@users.noreply.github.com>