Add ClassID GUIDs to COM servers. Also, update winrt::create_instance calls to use the ClassID instead of interface IDs.
Using new random GUIDs from guidgen.

This fixes the following compiler errors introduced by the previous commit:
C:\Dev\microsoft_wil\include\wil\cppwinrt_register_com_server.h(51): error C2787: 'MyServer': no GUID has been associated with this object
  C:\Dev\microsoft_wil\include\wil/cppwinrt_register_com_server.h(51): note: the template instantiation context (the oldest one first) is
  C:\Dev\microsoft_wil\tests\CppWinRTComServerTests.cpp(74): note: see reference to function template instantiation 'std::vector<wil::unique_com_class_object_cookie,std::allocator<wil::unique_com_class_object_cookie>> wil::register_com_server<MyServer,>(void)' being compiled
  C:\Dev\microsoft_wil\include\wil/cppwinrt_register_com_server.h(70): note: see reference to function template instantiation 'void wil::details::register_com_server<MyServer,>(std::vector<wil::unique_com_class_object_cookie,std::allocator<wil::unique_com_class_object_cookie>> &)' being compiled
C:\Dev\microsoft_wil\include\wil\cppwinrt_register_com_server.h(51): error C2787: 'BuggyServer': no GUID has been associated with this object
  C:\Dev\microsoft_wil\include\wil/cppwinrt_register_com_server.h(51): note: the template instantiation context (the oldest one first) is
  C:\Dev\microsoft_wil\tests\CppWinRTComServerTests.cpp(94): note: see reference to function template instantiation 'std::vector<wil::unique_com_class_object_cookie,std::allocator<wil::unique_com_class_object_cookie>> wil::register_com_server<BuggyServer,>(void)' being compiled
  C:\Dev\microsoft_wil\include\wil/cppwinrt_register_com_server.h(70): note: see reference to function template instantiation 'void wil::details::register_com_server<BuggyServer,>(std::vector<wil::unique_com_class_object_cookie,std::allocator<wil::unique_com_class_object_cookie>> &)' being compiled